// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/wallet.proto

package walletpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveKeyIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKeyIDRequest) Reset() {
	*x = ResolveKeyIDRequest{}
	mi := &file_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKeyIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKeyIDRequest) ProtoMessage() {}

func (x *ResolveKeyIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKeyIDRequest.ProtoReflect.Descriptor instead.
func (*ResolveKeyIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveKeyIDRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type ResolveKeyIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyIds        []string               `protobuf:"bytes,1,rep,name=key_ids,json=keyIds,proto3" json:"key_ids,omitempty"`
	CurrentKeyId  string                 `protobuf:"bytes,2,opt,name=current_key_id,json=currentKeyId,proto3" json:"current_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveKeyIDResponse) Reset() {
	*x = ResolveKeyIDResponse{}
	mi := &file_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveKeyIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveKeyIDResponse) ProtoMessage() {}

func (x *ResolveKeyIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveKeyIDResponse.ProtoReflect.Descriptor instead.
func (*ResolveKeyIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveKeyIDResponse) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

func (x *ResolveKeyIDResponse) GetCurrentKeyId() string {
	if x != nil {
		return x.CurrentKeyId
	}
	return ""
}

type OnConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Confirmations int32                  `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,6,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	EventId       string                 `protobuf:"bytes,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	IsFinalized   bool                   `protobuf:"varint,8,opt,name=is_finalized,json=isFinalized,proto3" json:"is_finalized,omitempty"`
	WithdrawalId  string                 `protobuf:"bytes,9,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnConfirmationRequest) Reset() {
	*x = OnConfirmationRequest{}
	mi := &file_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnConfirmationRequest) ProtoMessage() {}

func (x *OnConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnConfirmationRequest.ProtoReflect.Descriptor instead.
func (*OnConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *OnConfirmationRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *OnConfirmationRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *OnConfirmationRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *OnConfirmationRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OnConfirmationRequest) GetConfirmations() int32 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *OnConfirmationRequest) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *OnConfirmationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OnConfirmationRequest) GetIsFinalized() bool {
	if x != nil {
		return x.IsFinalized
	}
	return false
}

func (x *OnConfirmationRequest) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

type OnReorgRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHeight   int64                  `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Asset         string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	EventId       string                 `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Outpoints     []string               `protobuf:"bytes,5,rep,name=outpoints,proto3" json:"outpoints,omitempty"`
	WithdrawalId  string                 `protobuf:"bytes,6,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnReorgRequest) Reset() {
	*x = OnReorgRequest{}
	mi := &file_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnReorgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnReorgRequest) ProtoMessage() {}

func (x *OnReorgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnReorgRequest.ProtoReflect.Descriptor instead.
func (*OnReorgRequest) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *OnReorgRequest) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *OnReorgRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *OnReorgRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *OnReorgRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OnReorgRequest) GetOutpoints() []string {
	if x != nil {
		return x.Outpoints
	}
	return nil
}

func (x *OnReorgRequest) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_wallet_proto_rawDescGZIP(), []int{4}
}

var File_proto_wallet_proto protoreflect.FileDescriptor

const file_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wallet.proto\x12\x06wallet\"2\n" +
	"\x13ResolveKeyIDRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"U\n" +
	"\x14ResolveKeyIDResponse\x12\x17\n" +
	"\akey_ids\x18\x01 \x03(\tR\x06keyIds\x12$\n" +
	"\x0ecurrent_key_id\x18\x02 \x01(\tR\fcurrentKeyId\"\xa7\x02\n" +
	"\x15OnConfirmationRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12$\n" +
	"\rconfirmations\x18\x05 \x01(\x05R\rconfirmations\x12!\n" +
	"\fblock_height\x18\x06 \x01(\x03R\vblockHeight\x12\x19\n" +
	"\bevent_id\x18\a \x01(\tR\aeventId\x12!\n" +
	"\fis_finalized\x18\b \x01(\bR\visFinalized\x12#\n" +
	"\rwithdrawal_id\x18\t \x01(\tR\fwithdrawalId\"\xc4\x01\n" +
	"\x0eOnReorgRequest\x12!\n" +
	"\fblock_height\x18\x01 \x01(\x03R\vblockHeight\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\x12\x1c\n" +
	"\toutpoints\x18\x05 \x03(\tR\toutpoints\x12#\n" +
	"\rwithdrawal_id\x18\x06 \x01(\tR\fwithdrawalId\"\a\n" +
	"\x05Empty2\xcc\x01\n" +
	"\rWalletService\x12I\n" +
	"\fResolveKeyID\x12\x1b.wallet.ResolveKeyIDRequest\x1a\x1c.wallet.ResolveKeyIDResponse\x12>\n" +
	"\x0eOnConfirmation\x12\x1d.wallet.OnConfirmationRequest\x1a\r.wallet.Empty\x120\n" +
	"\aOnReorg\x12\x16.wallet.OnReorgRequest\x1a\r.wallet.EmptyBAZ?github.com/ai-crypto-onramp/wallet-manager/internal/pb;walletpbb\x06proto3"

var (
	file_proto_wallet_proto_rawDescOnce sync.Once
	file_proto_wallet_proto_rawDescData []byte
)

func file_proto_wallet_proto_rawDescGZIP() []byte {
	file_proto_wallet_proto_rawDescOnce.Do(func() {
		file_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)))
	})
	return file_proto_wallet_proto_rawDescData
}

var file_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_wallet_proto_goTypes = []any{
	(*ResolveKeyIDRequest)(nil),   // 0: wallet.ResolveKeyIDRequest
	(*ResolveKeyIDResponse)(nil),  // 1: wallet.ResolveKeyIDResponse
	(*OnConfirmationRequest)(nil), // 2: wallet.OnConfirmationRequest
	(*OnReorgRequest)(nil),        // 3: wallet.OnReorgRequest
	(*Empty)(nil),                 // 4: wallet.Empty
}
var file_proto_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.WalletService.ResolveKeyID:input_type -> wallet.ResolveKeyIDRequest
	2, // 1: wallet.WalletService.OnConfirmation:input_type -> wallet.OnConfirmationRequest
	3, // 2: wallet.WalletService.OnReorg:input_type -> wallet.OnReorgRequest
	1, // 3: wallet.WalletService.ResolveKeyID:output_type -> wallet.ResolveKeyIDResponse
	4, // 4: wallet.WalletService.OnConfirmation:output_type -> wallet.Empty
	4, // 5: wallet.WalletService.OnReorg:output_type -> wallet.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_wallet_proto_init() }
func file_proto_wallet_proto_init() {
	if File_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wallet_proto_rawDesc), len(file_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wallet_proto_goTypes,
		DependencyIndexes: file_proto_wallet_proto_depIdxs,
		MessageInfos:      file_proto_wallet_proto_msgTypes,
	}.Build()
	File_proto_wallet_proto = out.File
	file_proto_wallet_proto_goTypes = nil
	file_proto_wallet_proto_depIdxs = nil
}
