// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: proto/wallet.proto

package walletpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_ResolveKeyID_FullMethodName   = "/wallet.WalletService/ResolveKeyID"
	WalletService_OnConfirmation_FullMethodName = "/wallet.WalletService/OnConfirmation"
	WalletService_OnReorg_FullMethodName        = "/wallet.WalletService/OnReorg"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WalletService is served by wallet-management for MPC Signing and
// Blockchain Gateway integration.
type WalletServiceClient interface {
	// ResolveKeyID returns the active MPC key_id(s) bound to a wallet.
	ResolveKeyID(ctx context.Context, in *ResolveKeyIDRequest, opts ...grpc.CallOption) (*ResolveKeyIDResponse, error)
	// OnConfirmation is a Blockchain Gateway confirmation callback.
	OnConfirmation(ctx context.Context, in *OnConfirmationRequest, opts ...grpc.CallOption) (*Empty, error)
	// OnReorg is a Blockchain Gateway reorg callback.
	OnReorg(ctx context.Context, in *OnReorgRequest, opts ...grpc.CallOption) (*Empty, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) ResolveKeyID(ctx context.Context, in *ResolveKeyIDRequest, opts ...grpc.CallOption) (*ResolveKeyIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveKeyIDResponse)
	err := c.cc.Invoke(ctx, WalletService_ResolveKeyID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) OnConfirmation(ctx context.Context, in *OnConfirmationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WalletService_OnConfirmation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) OnReorg(ctx context.Context, in *OnReorgRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WalletService_OnReorg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
//
// WalletService is served by wallet-management for MPC Signing and
// Blockchain Gateway integration.
type WalletServiceServer interface {
	// ResolveKeyID returns the active MPC key_id(s) bound to a wallet.
	ResolveKeyID(context.Context, *ResolveKeyIDRequest) (*ResolveKeyIDResponse, error)
	// OnConfirmation is a Blockchain Gateway confirmation callback.
	OnConfirmation(context.Context, *OnConfirmationRequest) (*Empty, error)
	// OnReorg is a Blockchain Gateway reorg callback.
	OnReorg(context.Context, *OnReorgRequest) (*Empty, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) ResolveKeyID(context.Context, *ResolveKeyIDRequest) (*ResolveKeyIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveKeyID not implemented")
}
func (UnimplementedWalletServiceServer) OnConfirmation(context.Context, *OnConfirmationRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnConfirmation not implemented")
}
func (UnimplementedWalletServiceServer) OnReorg(context.Context, *OnReorgRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnReorg not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_ResolveKeyID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveKeyIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ResolveKeyID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ResolveKeyID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ResolveKeyID(ctx, req.(*ResolveKeyIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_OnConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).OnConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_OnConfirmation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).OnConfirmation(ctx, req.(*OnConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_OnReorg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnReorgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).OnReorg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_OnReorg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).OnReorg(ctx, req.(*OnReorgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveKeyID",
			Handler:    _WalletService_ResolveKeyID_Handler,
		},
		{
			MethodName: "OnConfirmation",
			Handler:    _WalletService_OnConfirmation_Handler,
		},
		{
			MethodName: "OnReorg",
			Handler:    _WalletService_OnReorg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wallet.proto",
}
